### Name: gadget_file
### Title: Gadget file objects
### Aliases: gadget_file print.gadget_file as.character.gadget_file
###   read.gadget_file

### ** Examples

# Simple key/values
gadget_file("age", components = list(
    list(length = 5, age = 1:5)))
## Not run: 
##D ; Generated by mfdb 1.0
##D length	5
##D age	1	2	3	4	5
## End(Not run)

# Multiple components
gadget_file("likelihood", components = list(
    list(),
    component = structure(list(type = "penalty"), preamble = list("comment")),
    component = structure(list(type = "penalty"), preamble = list("", "another comment"))))
## Not run: 
##D ; Generated by mfdb 1.0
##D ; comment
##D [component]
##D type	penalty
##D ; 
##D ; another comment
##D [component]
##D type	penalty
## End(Not run)

# Data
gadget_file("agelen", components = list(
    list(stocknames = "big boat")), data = data.frame(
    area = c(102, 103),
    number = c(2345, 5023)))
## Not run: 
##D ; Generated by mfdb 1.0
##D stocknames	big	boat
##D ; -- data --
##D ; area number
##D 102	2345
##D 103	5023
## End(Not run)



